# Site settings
title: Sushi2 documantation
email: miljs@mi.t.u-tokyo.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  Sushi2 is a matrix library for JavaScript.
baseurl: "/sushi2" # the subpath of your site, e.g. /blog/
url: "https://mil-tokyo.github.com" # the base hostname & protocol for your site
github_username:  mil-tokyo
theme: minima

# Build settings
markdown: kramdown
keep_files: ["api"]
exclude: ["Gemfile", "Gemfile.lock"]
